/* Generated By:JJTree: Do not edit this line. ASTSimpleBoolean.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTSimpleBoolean extends SimpleNode {
  public ASTSimpleBoolean(int id) {
    super(id);
  }

  public ASTSimpleBoolean(FilterParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FilterParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=56d3de0faa8ca9851f38d45fe8a99ea9 (do not edit this line) */
