/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTCOMPARISON = 1;
  public int JJTSIMPLEBOOLEAN = 2;
  public int JJTVOID = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Comparison",
    "SimpleBoolean",
    "void",
  };
}
/* JavaCC - OriginalChecksum=80dce593c357ee41f5a3544e07dfcbf0 (do not edit this line) */
