/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTComparison node, Object data);
  public Object visit(ASTSimpleBoolean node, Object data);
}
/* JavaCC - OriginalChecksum=b4361faf03d0d12895b971df12379dbb (do not edit this line) */
