/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, VisitorData data);
  public Object visit(ASTExpression node, VisitorData data);
  public Object visit(ASTComparison node, VisitorData data);
  public Object visit(ASTIdentifier node, VisitorData data);
}
/* JavaCC - OriginalChecksum=3551aa09f5ff0db40d3356a486295ac0 (do not edit this line) */
