/* Generated By:JavaCC: Do not edit this line. FilterParserDefaultVisitor.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public class FilterParserDefaultVisitor implements FilterParserVisitor{
  public Object defaultVisit(SimpleNode node, VisitorData data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, VisitorData data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, VisitorData data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComparison node, VisitorData data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, VisitorData data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=c021a1798ae6184947ae69fb89f482a0 (do not edit this line) */
