/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTCOMPARISON = 2;
  public int JJTIDENTIFIER = 3;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Comparison",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=c0dee8aab826bfb6706b784e3701efc6 (do not edit this line) */
