/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTAND extends SimpleNode {
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56884230bced6f572179d2f2f9033f07 (do not edit this line) */
