/* Generated By:JJTree: Do not edit this line. ASTBRACKETS.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTBRACKETS extends SimpleNode {
  public ASTBRACKETS(int id) {
    super(id);
  }

  public ASTBRACKETS(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c35db67a4ff2d23fdd123a273fa91d8 (do not edit this line) */
