/* Generated By:JJTree: Do not edit this line. ASTBOOLEAN.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTBOOLEAN extends SimpleNode {
  public ASTBOOLEAN(int id) {
    super(id);
  }

  public ASTBOOLEAN(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f34c525f4cf78c27d0330c562f055c87 (do not edit this line) */
