/* Generated By:JJTree: Do not edit this line. ASTBooleanComparison.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTBooleanComparison extends SimpleNode {
  public ASTBooleanComparison(int id) {
    super(id);
  }

  public ASTBooleanComparison(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a71e87a36b1f95889d5321a1d66fe009 (do not edit this line) */
