/* Generated By:JJTree: Do not edit this line. ASTBRACKETEDFILTER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTBRACKETEDFILTER extends SimpleNode {
  public ASTBRACKETEDFILTER(int id) {
    super(id);
  }

  public ASTBRACKETEDFILTER(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8c60d8e901dc499e841061ad3c688d3 (do not edit this line) */
