/* Generated By:JJTree: Do not edit this line. ASTBooleanOperator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTBooleanOperator extends SimpleNode {
  public ASTBooleanOperator(int id) {
    super(id);
  }

  public ASTBooleanOperator(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3f60719a50b6b3265ff2a39df49ced4 (do not edit this line) */
