/* Generated By:JJTree: Do not edit this line. ASTBOOLEANIDENTIFIER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTBOOLEANIDENTIFIER extends SimpleNode {
  public ASTBOOLEANIDENTIFIER(int id) {
    super(id);
  }

  public ASTBOOLEANIDENTIFIER(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8ed88f54e553f7a4297ce74f462c1f83 (do not edit this line) */
