/* Generated By:JJTree: Do not edit this line. ASTCONTAINS.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTCONTAINS extends SimpleNode {
  public ASTCONTAINS(int id) {
    super(id);
  }

  public ASTCONTAINS(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d474b642f018c87d94b75e6d8c7de673 (do not edit this line) */
