/* Generated By:JJTree: Do not edit this line. ASTCOMPARISON.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTCOMPARISON extends SimpleNode {
  public ASTCOMPARISON(int id) {
    super(id);
  }

  public ASTCOMPARISON(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25712922251159d2db146f3e6892ba92 (do not edit this line) */
