/* Generated By:JJTree: Do not edit this line. ASTEXPR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTEXPR extends SimpleNode {
  public ASTEXPR(int id) {
    super(id);
  }

  public ASTEXPR(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea840885fdaf8a2969e38c17187e783c (do not edit this line) */
