/* Generated By:JJTree: Do not edit this line. ASTEXPRESSION.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTEXPRESSION extends SimpleNode {
  public ASTEXPRESSION(int id) {
    super(id);
  }

  public ASTEXPRESSION(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f2e4b78f698b073cb76c5bee6fd8621 (do not edit this line) */
