/* Generated By:JJTree: Do not edit this line. ASTEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTEQ extends SimpleNode {
  public ASTEQ(int id) {
    super(id);
  }

  public ASTEQ(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d94c00d190261d785d678fd64d59e62a (do not edit this line) */
