/* Generated By:JJTree: Do not edit this line. ASTFILTER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTFILTER extends SimpleNode {
  public ASTFILTER(int id) {
    super(id);
  }

  public ASTFILTER(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=679248ef7d63490ed2a6966b2ddc9f82 (do not edit this line) */
