/* Generated By:JJTree: Do not edit this line. ASTFILTER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTFILTER extends SimpleNode {

  protected boolean inverse=false;

  public ASTFILTER(int id) {
    super(id);
  }

  public ASTFILTER(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f1b515efbec8642bf19564a1fc77f03 (do not edit this line) */
