/* Generated By:JJTree: Do not edit this line. ASTGEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTGEQ extends SimpleNode {
  public ASTGEQ(int id) {
    super(id);
  }

  public ASTGEQ(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f54fb8f2ccaa619ab8f2bc17c6b92cd (do not edit this line) */
