/* Generated By:JJTree: Do not edit this line. ASTGT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTGT extends SimpleNode {
  public ASTGT(int id) {
    super(id);
  }

  public ASTGT(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f27ab2b191ba9a8e4f7a82fb6da65d6 (do not edit this line) */
