/* Generated By:JJTree: Do not edit this line. ASTINVERSE.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTINVERSE extends SimpleNode {
  public ASTINVERSE(int id) {
    super(id);
  }

  public ASTINVERSE(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b82f80da4a2e56dddd237a1d5e5b691f (do not edit this line) */
