/* Generated By:JJTree: Do not edit this line. ASTLEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTLEQ extends SimpleNode {
  public ASTLEQ(int id) {
    super(id);
  }

  public ASTLEQ(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22c1e5157038a0ddfee8ec1edc3f9a51 (do not edit this line) */
