/* Generated By:JJTree: Do not edit this line. ASTLT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5546f8b8738deca530cf2cc74f5b8a12 (do not edit this line) */
