/* Generated By:JJTree: Do not edit this line. ASTLParen.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTLParen extends SimpleNode {
  public ASTLParen(int id) {
    super(id);
  }

  public ASTLParen(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8274063ba3f70d683285f597329ec700 (do not edit this line) */
