/* Generated By:JJTree: Do not edit this line. ASTLEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTLEQ extends SimpleNode {
  public ASTLEQ(int id) {
    super(id);
  }

  public ASTLEQ(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8d1dea3b05cd7899bc8361f993581c0 (do not edit this line) */
