/* Generated By:JJTree: Do not edit this line. ASTNUMBER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTNUMBER extends SimpleNode {
  public ASTNUMBER(int id) {
    super(id);
  }

  public ASTNUMBER(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=672ae768004bb5cc322fee7ec718de25 (do not edit this line) */
