/* Generated By:JJTree: Do not edit this line. ASTNEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTNEQ extends SimpleNode {
  public ASTNEQ(int id) {
    super(id);
  }

  public ASTNEQ(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b336ae3be68511065e157f57d384dfde (do not edit this line) */
