/* Generated By:JJTree: Do not edit this line. ASTNumericalComparison.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTNumericalComparison extends SimpleNode {
  public ASTNumericalComparison(int id) {
    super(id);
  }

  public ASTNumericalComparison(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a2979c6b7a7129f851fd123a5d70cebd (do not edit this line) */
