/* Generated By:JJTree: Do not edit this line. ASTNEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTNEQ extends SimpleNode {
  public ASTNEQ(int id) {
    super(id);
  }

  public ASTNEQ(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26e6b887042d40513c074a58e219a976 (do not edit this line) */
