/* Generated By:JJTree: Do not edit this line. ASTOR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTOR extends SimpleNode {
  public ASTOR(int id) {
    super(id);
  }

  public ASTOR(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a1f99bb54c1fee66e9a3d090f26ea66 (do not edit this line) */
