/* Generated By:JJTree: Do not edit this line. ASTREGEX.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTREGEX extends SimpleNode {
  public ASTREGEX(int id) {
    super(id);
  }

  public ASTREGEX(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb91770eb75786ddb75155d534fa8218 (do not edit this line) */
