/* Generated By:JJTree: Do not edit this line. ASTRoot.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTRoot extends SimpleNode {
  public ASTRoot(int id) {
    super(id);
  }

  public ASTRoot(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d9fc4d90318c828ba04bbea5ed475f0 (do not edit this line) */
