/* Generated By:JJTree: Do not edit this line. ASTRParen.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTRParen extends SimpleNode {
  public ASTRParen(int id) {
    super(id);
  }

  public ASTRParen(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f59817734958bdf010f16f6202cf3f08 (do not edit this line) */
