/* Generated By:JJTree: Do not edit this line. ASTROOT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTROOT extends SimpleNode {
  public ASTROOT(int id) {
    super(id);
  }

  public ASTROOT(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c007f428ed44d3045f3a4e747a8be7f (do not edit this line) */
