/* Generated By:JJTree: Do not edit this line. ASTRootFilter.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTRootFilter extends SimpleNode {
  public ASTRootFilter(int id) {
    super(id);
  }

  public ASTRootFilter(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3fc5f9cea008b7d87b5138bd93fca728 (do not edit this line) */
