/* Generated By:JJTree: Do not edit this line. ASTSTRING.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTSTRING extends SimpleNode {
  public ASTSTRING(int id) {
    super(id);
  }

  public ASTSTRING(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21d3e9139bbe82ea54ef2459b9808e7d (do not edit this line) */
