/* Generated By:JJTree: Do not edit this line. ASTStringComparison.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTStringComparison extends SimpleNode {
  public ASTStringComparison(int id) {
    super(id);
  }

  public ASTStringComparison(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=801de1644715ff785267cdd8ece94b0b (do not edit this line) */
