/* Generated By:JJTree: Do not edit this line. ASTUNBRACKETEDFILTER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTUNBRACKETEDFILTER extends SimpleNode {
  public ASTUNBRACKETEDFILTER(int id) {
    super(id);
  }

  public ASTUNBRACKETEDFILTER(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82ee7c498f214d2403d9e7949e9b5641 (do not edit this line) */
