/* Generated By:JJTree: Do not edit this line. ASTXOR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTXOR extends SimpleNode {
  public ASTXOR(int id) {
    super(id);
  }

  public ASTXOR(FilterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9680c5f9e9b81d1f29a3ca712b5ead5 (do not edit this line) */
