/* Generated By:JJTree: Do not edit this line. ASTXOR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package loggerplusplus.filter.parser;

public
class ASTXOR extends SimpleNode {
  public ASTXOR(int id) {
    super(id);
  }

  public ASTXOR(SyntaxChecker p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c5aa44d92d041a6637638de6dc92430 (do not edit this line) */
