/* Generated By:JJTree&JavaCC: Do not edit this line. FilterParserConstants.java */
package loggerplusplus.filter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 2;
  /** RegularExpression Id. */
  int NEQ = 3;
  /** RegularExpression Id. */
  int GT = 4;
  /** RegularExpression Id. */
  int LT = 5;
  /** RegularExpression Id. */
  int GEQ = 6;
  /** RegularExpression Id. */
  int LEQ = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int XOR = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int SINGLEQUOTEDSTRING = 12;
  /** RegularExpression Id. */
  int DOUBLEQUOTEDSTRING = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int REGEXLITERAL = 16;
  /** RegularExpression Id. */
  int REGEX = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int INVERSE = 21;
  /** RegularExpression Id. */
  int CONTAINS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EQ>",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<OR>",
    "<AND>",
    "<XOR>",
    "<BOOLEAN>",
    "<SINGLEQUOTEDSTRING>",
    "<DOUBLEQUOTEDSTRING>",
    "<NUMBER>",
    "<DIGIT>",
    "<REGEXLITERAL>",
    "<REGEX>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "<INVERSE>",
    "<CONTAINS>",
  };

}
