/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTFILTER = 1;
  public int JJTEXPRESSION = 2;
  public int JJTBOOLEANCOMPARISON = 3;
  public int JJTNUMERICALCOMPARISON = 4;
  public int JJTSTRINGCOMPARISON = 5;
  public int JJTNUMBER = 6;
  public int JJTSTRING = 7;
  public int JJTREGEX = 8;
  public int JJTBOOLEANIDENTIFIER = 9;
  public int JJTBOOLEAN = 10;
  public int JJTBOOLEANOPERATOR = 11;
  public int JJTCONTAINS = 12;
  public int JJTEQ = 13;
  public int JJTNEQ = 14;
  public int JJTGT = 15;
  public int JJTGEQ = 16;
  public int JJTLT = 17;
  public int JJTLEQ = 18;
  public int JJTAND = 19;
  public int JJTOR = 20;
  public int JJTXOR = 21;


  public String[] jjtNodeName = {
    "ROOT",
    "FILTER",
    "EXPRESSION",
    "BooleanComparison",
    "NumericalComparison",
    "StringComparison",
    "NUMBER",
    "STRING",
    "REGEX",
    "BOOLEANIDENTIFIER",
    "BOOLEAN",
    "BooleanOperator",
    "CONTAINS",
    "EQ",
    "NEQ",
    "GT",
    "GEQ",
    "LT",
    "LEQ",
    "AND",
    "OR",
    "XOR",
  };
}
/* JavaCC - OriginalChecksum=9cc16b8df71dd17fde76be56d0252d51 (do not edit this line) */
