/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTreeConstants.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface SyntaxCheckerTreeConstants
{
  public int JJTFILTER = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTCOMPARISON = 3;
  public int JJTINVERSE = 4;
  public int JJTNUMBER = 5;
  public int JJTSTRING = 6;
  public int JJTREGEX = 7;
  public int JJTIDENTIFIER = 8;
  public int JJTBOOLEAN = 9;
  public int JJTEQ = 10;
  public int JJTNEQ = 11;
  public int JJTGT = 12;
  public int JJTGEQ = 13;
  public int JJTLT = 14;
  public int JJTLEQ = 15;
  public int JJTAND = 16;
  public int JJTOR = 17;
  public int JJTXOR = 18;


  public String[] jjtNodeName = {
    "FILTER",
    "EXPRESSION",
    "void",
    "COMPARISON",
    "INVERSE",
    "NUMBER",
    "STRING",
    "REGEX",
    "IDENTIFIER",
    "BOOLEAN",
    "EQ",
    "NEQ",
    "GT",
    "GEQ",
    "LT",
    "LEQ",
    "AND",
    "OR",
    "XOR",
  };
}
/* JavaCC - OriginalChecksum=ecb4a263e5e95a4355fdd40c104eee98 (do not edit this line) */
