/* Generated By:JJTree&JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package loggerplusplus.filter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 5;
  /** RegularExpression Id. */
  int NEQ = 6;
  /** RegularExpression Id. */
  int GT = 7;
  /** RegularExpression Id. */
  int LT = 8;
  /** RegularExpression Id. */
  int GEQ = 9;
  /** RegularExpression Id. */
  int LEQ = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int XOR = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int SINGLEQUOTEDSTRING = 15;
  /** RegularExpression Id. */
  int DOUBLEQUOTEDSTRING = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int REGEX = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<EQ>",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<OR>",
    "<AND>",
    "<XOR>",
    "<BOOLEAN>",
    "<SINGLEQUOTEDSTRING>",
    "<DOUBLEQUOTEDSTRING>",
    "<NUMBER>",
    "<DIGIT>",
    "<REGEX>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
  };

}
