/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTreeConstants.java Version 7.0.2 */
package loggerplusplus.filter.parser;

public interface SyntaxCheckerTreeConstants
{
  public int JJTFILTER = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTCOMPARISON = 3;
  public int JJTNUMBER = 4;
  public int JJTSTRING = 5;
  public int JJTREGEX = 6;
  public int JJTIDENTIFIER = 7;
  public int JJTBOOLEAN = 8;
  public int JJTEQ = 9;
  public int JJTNEQ = 10;
  public int JJTGT = 11;
  public int JJTGEQ = 12;
  public int JJTLT = 13;
  public int JJTLEQ = 14;
  public int JJTAND = 15;
  public int JJTOR = 16;
  public int JJTXOR = 17;


  public String[] jjtNodeName = {
    "FILTER",
    "EXPRESSION",
    "void",
    "COMPARISON",
    "NUMBER",
    "STRING",
    "REGEX",
    "IDENTIFIER",
    "BOOLEAN",
    "EQ",
    "NEQ",
    "GT",
    "GEQ",
    "LT",
    "LEQ",
    "AND",
    "OR",
    "XOR",
  };
}
/* JavaCC - OriginalChecksum=3e091f2ef3f48a239462829578701c0b (do not edit this line) */
