/* Generated By:JavaCC: Do not edit this line. FilterParserDefaultVisitor.java Version 7.0.2 */
package com.nccgroup.loggerplusplus.filter.parser;

import com.nccgroup.loggerplusplus.filter.savedfilter.SavedFilter;
import com.nccgroup.loggerplusplus.filterlibrary.FilterLibraryController;
import com.nccgroup.loggerplusplus.logentry.FieldGroup;
import com.nccgroup.loggerplusplus.logentry.LogEntryField;

import java.util.HashSet;
import java.util.LinkedList;

public class AliasCheckVisitor implements FilterParserVisitor{

  private FilterLibraryController filterLibraryController;

  public AliasCheckVisitor(FilterLibraryController filterLibraryController){
    this.filterLibraryController = filterLibraryController;
  }

  public VisitorData defaultVisit(SimpleNode node, VisitorData data){
    node.childrenAccept(this, data);
    return data;
  }
  public VisitorData visit(SimpleNode node, VisitorData data){
    return defaultVisit(node, data);
  }

  public VisitorData visit(SimpleNode node){
    VisitorData visitorData = new VisitorData();
    visitorData.setData("dependencies", new HashSet<String>());
    visitorData.setData("contexts", new HashSet<FieldGroup>());
    visitorData.setData("aliasVisitList", new LinkedList<String>());
    return visit(node, visitorData);
  }
  public VisitorData visit(ASTExpression node, VisitorData data){
    return defaultVisit(node, data);
  }
  public VisitorData visit(ASTComparison node, VisitorData visitorData){
    HashSet<FieldGroup> contexts = (HashSet<FieldGroup>) visitorData.getData().get("contexts");
    if(node.left instanceof LogEntryField) contexts.add(((LogEntryField) node.left).getFieldGroup());
    if(node.right instanceof LogEntryField) contexts.add(((LogEntryField) node.right).getFieldGroup());
    defaultVisit(node, visitorData);
    return visitorData;
  }

  private static String RECURSION_CHECK = "RECURSION_CHECK";
  @Override
  public VisitorData visit(ASTAlias node, VisitorData data) {
    //Add this alias to our dependencies
    ((HashSet<String>) data.getData().get("dependencies")).add(node.identifier);
    if(filterLibraryController == null){
      data.addError("Cannot use aliases in this context. Filter library controller is not set.");
      return data;
    }

    LinkedList<String> aliasVisitList = (LinkedList<String>) data.getData().get("aliasVisitList");
    if(aliasVisitList.contains(node.identifier)){
      //We're recursing, don't continue!
      data.addError("Recursion detected in filter. Alias identifier: " + node.identifier);
      return data;
    }else{
      aliasVisitList.push(node.identifier);
    }

    //Now sanity check on the aliased filter with our existing data
    boolean foundAliasedFilter = false;
    for (SavedFilter savedFilter : filterLibraryController.getFilterSnippets()) {
      if(savedFilter.getName().equalsIgnoreCase(node.identifier) && savedFilter.getFilterExpression() != null){
        visit(savedFilter.getFilterExpression().getAst(), data);
        foundAliasedFilter = true;
        aliasVisitList.pop();
        break;
      }
    }

    if(!foundAliasedFilter){
      data.addError("Could not find a filter in the library for alias: " + node.identifier);
    }

    return data;
  }
}
/* JavaCC - OriginalChecksum=b30458d637879c9662107beea18204f0 (do not edit this line) */
