/* Generated By:JJTree&JavaCC: Do not edit this line. FilterParserConstants.java */
package com.nccgroup.loggerplusplus.filter.parser;


/**
 * Token literal groups and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 2;
  /** RegularExpression Id. */
  int NEQ = 3;
  /** RegularExpression Id. */
  int GT = 4;
  /** RegularExpression Id. */
  int LT = 5;
  /** RegularExpression Id. */
  int GEQ = 6;
  /** RegularExpression Id. */
  int LEQ = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int XOR = 10;
  /** RegularExpression Id. */
  int CONTAINS = 11;
  /** RegularExpression Id. */
  int IN = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int SINGLEQUOTEDSTRING = 14;
  /** RegularExpression Id. */
  int DOUBLEQUOTEDSTRING = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int REGEXLITERAL = 18;
  /** RegularExpression Id. */
  int REGEX = 19;
  /** RegularExpression Id. */
  int LPAREN = 20;
  /** RegularExpression Id. */
  int RPAREN = 21;
  /** RegularExpression Id. */
  int INVERSE = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int ARRAY_START = 25;
  /** RegularExpression Id. */
  int ARRAY_END = 26;
  /** RegularExpression Id. */
  int ARRAY_SEPARATOR = 27;
  /** RegularExpression Id. */
  int ALIAS_SYMBOL = 28;
  /** RegularExpression Id. */
  int ALIAS_IDENTIFIER = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token groups. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EQ>",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<OR>",
    "<AND>",
    "<XOR>",
    "\"CONTAINS\"",
    "\"IN\"",
    "<BOOLEAN>",
    "<SINGLEQUOTEDSTRING>",
    "<DOUBLEQUOTEDSTRING>",
    "<NUMBER>",
    "<DIGIT>",
    "<REGEXLITERAL>",
    "<REGEX>",
    "\"(\"",
    "\")\"",
    "<INVERSE>",
    "\".\"",
    "<IDENTIFIER>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"#\"",
    "<ALIAS_IDENTIFIER>",
  };

}
