/* Generated By:JavaCC: Do not edit this line. FilterParserDefaultVisitor.java Version 7.0.2 */
package com.nccgroup.loggerplusplus.filter.parser;

public class FilterParserDefaultVisitor implements FilterParserVisitor{
  public Object defaultVisit(SimpleNode node, VisitorData data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, VisitorData data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, VisitorData data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComparison node, VisitorData data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAlias node, VisitorData data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=06ac44fa53bd2978a8b7d3aa6de4fced (do not edit this line) */
