/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 7.0.2 */
package com.nccgroup.loggerplusplus.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, VisitorData data);
  public Object visit(ASTExpression node, VisitorData data);
  public Object visit(ASTComparison node, VisitorData data);
  public Object visit(ASTAlias node, VisitorData data);
}
/* JavaCC - OriginalChecksum=6fc9bf0937c416fc04e99e70768a04f7 (do not edit this line) */
