/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 7.0.2 */
package com.nccgroup.loggerplusplus.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, VisitorData data);
  public Object visit(ASTExpression node, VisitorData data);
  public Object visit(ASTComparison node, VisitorData data);
  public Object visit(ASTAlias node, VisitorData data);
  public Object visit(ASTIdentifier node, VisitorData data);
}
/* JavaCC - OriginalChecksum=108764213b791d483a795b3e60b5f9b9 (do not edit this line) */
