/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 5.0 */
package com.nccgroup.loggerplusplus.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, VisitorData data);
  public Object visit(ASTExpression node, VisitorData data);
  public Object visit(ASTComparison node, VisitorData data);
  public Object visit(ASTAlias node, VisitorData data);
}
/* JavaCC - OriginalChecksum=1d4b7dd7f55608a77745498f1be093dd (do not edit this line) */
