/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 7.0.2 */
package com.nccgroup.loggerplusplus.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTCOMPARISON = 2;
  public int JJTALIAS = 3;
  public int JJTIDENTIFIER = 4;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Comparison",
    "Alias",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=d9b13c87383c6581ca732e42be3d1d7a (do not edit this line) */
