/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 7.0.2 */
package com.nccgroup.loggerplusplus.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEXPRESSION = 1;
  public int JJTCOMPARISON = 2;
  public int JJTALIAS = 3;


  public String[] jjtNodeName = {
    "void",
    "Expression",
    "Comparison",
    "Alias",
  };
}
/* JavaCC - OriginalChecksum=b03fa3e64accc9245d958e2ed2a55041 (do not edit this line) */
