/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package com.nccgroup.loggerplusplus.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEXPRESSION = 1;
  public int JJTCOMPARISON = 2;
  public int JJTALIAS = 3;


  public String[] jjtNodeName = {
    "void",
    "Expression",
    "Comparison",
    "Alias",
  };
}
/* JavaCC - OriginalChecksum=a8f71270ce0cb112d3284149dfad33e2 (do not edit this line) */
